export const cards = [
    [ {content:"Who Is the main character of One Piece"},
      {content:"Monkey D. Luffy"},
    ] , 
    [ {content:"Who is the main villan of Bleach"},
      {content:"Aizen"},
    ] , 
    [ {content:"Who the creator of Hunter X Hunter"},
      {content:"Yoshihiro Togashi "},
    ] , 
    [ {content:"How many Dragon Balls are there"},
      {content:"7"},
    ] , 
    [ {content:"In Death Note, how does Light Yagami first discover the infamous notebook?"},
      {content:"He sees it fall from the sky"},
    ] , 
    [ {content:"Where is the scar located on Scar’s body in “Fullmetal Alchemist”"},
      {content:"His Face"},
    ] , 
    [ {content:"What is the name of the Curse occupying Yuji Itadori’s body in “Jujutsu Kaisen”"},
      {content:"Ryomen Sukuna"},
    ] , 
    [ {content:"Who is the child of Isabella by blood in “The Promised Neverland”?"},
      {content:"Ray"},
    ] , 
    [ {content:"How do the hokage come back to life in naruto"},
      {content:"Reanimation Jutsu"},
    ] , 
    [ {content:"In Code Gass who kills Lelouch "},
      {content:"Suzaku"},
    ]
   ]